### ISSUE TITLE
Validate that args is a list

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/sqlsynthgen#131]
In the table part of the config, 

```yaml
table_name:
  row_generators:
    - name: something
    - args:
         somekey: someval
```

it's quite easy to accidentally put  a dict under `args`. We should validate that this is a list
